name: audioplayers
description: A Flutter plugin to play multiple audio files simultaneously
version: 0.20.1
homepage: https://github.com/luanpotter/audioplayers

flutter:
  plugin:
    platforms:
      android:
        package: xyz.luan.audioplayers
        pluginClass: AudioplayersPlugin
      ios:
        pluginClass: AudioplayersPlugin
      macos:
        pluginClass: AudioplayersPlugin

dependencies:
  uuid: ^3.0.4
  path_provider: ^2.0.4
  http: ^0.13.3
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"